AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/BlockLength:
  ExcludedMethods: 'describe'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: 'double_quotes'

Style/FrozenStringLiteralComment:
  EnforcedStyle: 'never'
