AllCops:
  Exclude:
    - "bin/**/*"
    - "mache.gemspec"

Metrics/BlockLength:
  ExcludedMethods: describe

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
