AllCops:
  Exclude:
    - "bin/**/*"
    - "mache.gemspec"

Metrics/BlockLength:
  ExcludedMethods: describe

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
