AllCops:
  Exclude:
    - 'mache.gemspec'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  ExcludedMethods: ['describe']

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"
